// Hand-curated back-of-book index.
// Each entry references one or more section *titles*; the page number
// (chronological locator 01..N) is resolved at render time from outline.js,
// so reordering or adding sections keeps the index in sync.

export const categories = [
  {
    category: 'People',
    entries: [
      { name: 'Baddeley, Alan', refs: ['State-Dependent Retrieval'] },
      { name: 'Beckers, Tom', refs: ['Prediction Error Opens It'] },
      { name: 'Bellamy, Chyrell', refs: ['Certified Peer-Support Specialists'] },
      { name: 'Brown, Alan', refs: ['Healthy by Default'] },
      { name: 'Carhart-Harris, Robin', refs: ['Flow and the Default Mode'] },
      { name: 'Cleary, Anne', refs: ['The Gestalt Hypothesis'] },
      { name: 'Crichton, Michael', refs: ['The Terminal Man'] },
      { name: 'Csikszentmihalyi, Mihaly', refs: ['Flow and the Default Mode'] },
      { name: 'Davidson, Larry', refs: ['Certified Peer-Support Specialists'] },
      { name: 'Deci, Edward', refs: ['Self-Determination'] },
      { name: 'Ecker, Bruce', refs: ['Coherence Therapy'] },
      { name: 'Ferster, Charles', refs: ['Variable-Ratio Reinforcement'] },
      { name: 'Flaherty, Alice', refs: ['The Midnight Disease'] },
      { name: 'Garcia, Megan', refs: ['Garcia v. Character Technologies'] },
      { name: 'Godden, Duncan', refs: ['State-Dependent Retrieval'] },
      { name: 'Gottman, John', refs: ['The Four Horsemen', 'Turning Toward the Bid', 'Turning Toward'] },
      { name: 'Gross, James', refs: ['Reappraisal Beats Suppression', 'The At-Will Shift'] },
      { name: 'Haugen, Frances', refs: ['What Meta Knew'] },
      { name: 'Hebb, Donald', refs: ['The Hebbian Principle'] },
      { name: 'Hofstadter, Douglas', refs: ['The ELIZA Effect'] },
      { name: 'Hulley, Laurel', refs: ['Coherence Therapy'] },
      { name: 'Janet, Pierre', refs: ['Janet Before Freud'] },
      { name: 'Kalichman, Seth', refs: ['Disclosure Suppression', 'Iatrogenic Silence'] },
      { name: 'Kandel, Eric', refs: ['Synaptic Memory'] },
      { name: 'Kindt, Merel', refs: ['Prediction Error Opens It'] },
      { name: 'LeDoux, Joseph', refs: ['Reconsolidation', 'The Labile State'] },
      { name: 'Loftus, Elizabeth', refs: ['Loftus and the Mall'] },
      { name: 'Lupien, Sonia', refs: ['The Cortisol Aperture'] },
      { name: 'McAdams, Dan', refs: ['Narrative Identity'] },
      { name: 'McGaugh, James', refs: ['The Cortisol Aperture'] },
      { name: 'McNaughton, Bruce', refs: ['Sleep and Replay'] },
      { name: 'Merzenich, Michael', refs: ['Cortical Remapping'] },
      { name: 'Nader, Karim', refs: ['Reconsolidation', 'The Labile State'] },
      { name: 'Nedergaard, Maiken', refs: ['The Glymphatic Sweep'] },
      { name: 'Neff, Kristin', refs: ['Self-Compassion'] },
      { name: 'Nijenhuis, Ellert', refs: ['Structural Dissociation'] },
      { name: 'Nolen-Hoeksema, Susan', refs: ['The Rumination Trap'] },
      { name: 'Nurius, Paula', refs: ['Iatrogenic Silence'] },
      { name: 'O’Connor, Akira', refs: ['A Memory Verification Error', 'The Scanner Finding'] },
      { name: 'Orben, Amy', refs: ['The Magnitude Debate'] },
      { name: 'Oyserman, Daphna', refs: ['Identity-Based Cognition', 'Grounding in Identity'] },
      { name: 'Pascual-Leone, Alvaro', refs: ['Blind V1 Reads Braille'] },
      { name: 'Penfield, Wilder', refs: ['The Temporal Lobe'] },
      { name: 'Pennebaker, James', refs: ['Pennebaker’s Paradigm', 'The Writing Protocol'] },
      { name: 'Perez, Ethan', refs: ['Sycophancy'] },
      { name: 'Phillips, David', refs: ['Contagion'] },
      { name: 'Pickrell, Jacqueline', refs: ['Loftus and the Mall'] },
      { name: 'Przybylski, Andrew', refs: ['The Magnitude Debate'] },
      { name: 'Putnam, Frank', refs: ['The Dissociation Spectrum'] },
      { name: 'Raichle, Marcus', refs: ['Flow and the Default Mode'] },
      { name: 'Rogers, Carl', refs: ['The Listening'] },
      { name: 'Ryan, Richard', refs: ['Self-Determination'] },
      { name: 'Schafe, Glenn', refs: ['Reconsolidation', 'The Labile State'] },
      { name: 'Schwartz, Richard', refs: ['Internal Family Systems'] },
      { name: 'Setzer, Sewell', refs: ['Garcia v. Character Technologies'] },
      { name: 'Sevenster, Marieke', refs: ['Prediction Error Opens It'] },
      { name: 'Shapiro, Francine', refs: ['EMDR'] },
      { name: 'Skinner, B. F.', refs: ['Variable-Ratio Reinforcement'] },
      { name: 'Squire, Larry', refs: ['Consolidation'] },
      { name: 'Steele, Kathy', refs: ['Structural Dissociation'] },
      { name: 'Sweller, John', refs: ['Cognitive Load'] },
      { name: 'Taub, Edward', refs: ['Constraint-Induced Recovery'] },
      { name: 'Ticic, Robin', refs: ['Coherence Therapy'] },
      { name: 'Turkle, Sherry', refs: ['Turkle’s Continuation'] },
      { name: 'Twenge, Jean', refs: ['The 2012 Inflection'] },
      { name: 'Vaillant, George', refs: ['Vaillant’s Hierarchy'] },
      { name: 'van der Hart, Onno', refs: ['Structural Dissociation'] },
      { name: 'van der Kolk, Bessel', refs: ['Van der Kolk’s Counter'] },
      { name: 'Vaswani, Ashish', refs: ['Tokens, Not Thoughts'] },
      { name: 'Wegner, Daniel', refs: ['Suppression Costs'] },
      { name: 'Weizenbaum, Joseph', refs: ['ELIZA', 'The Secretary', 'Judgment, Not Calculation'] },
      { name: 'Wells, Adrian', refs: ['Metacognitive Distance'] },
      { name: 'Wilson, Bill', refs: ['A Searching and Fearless Inventory'] },
      { name: 'Wilson, Matthew', refs: ['Sleep and Replay'] },
      { name: 'Xie, Lulu', refs: ['The Glymphatic Sweep'] }
    ]
  },
  {
    category: 'Works',
    entries: [
      { name: '*Adaptation to Life* (Vaillant, 1977)', refs: ['Vaillant’s Hierarchy'] },
      { name: '*Alcoholics Anonymous* (Wilson, 1939)', refs: ['A Searching and Fearless Inventory'] },
      { name: '*Alone Together* (Turkle, 2011)', refs: ['Turkle’s Continuation'] },
      { name: '*Attention Is All You Need* (Vaswani et al., 2017)', refs: ['Tokens, Not Thoughts'] },
      { name: '*The Body Keeps the Score* (van der Kolk)', refs: ['Van der Kolk’s Counter'] },
      { name: '*Computer Power and Human Reason* (Weizenbaum, 1976)', refs: ['Judgment, Not Calculation'] },
      { name: '*The Haunted Self* (van der Hart, Nijenhuis, Steele, 2006)', refs: ['Structural Dissociation'] },
      { name: '*L’Automatisme Psychologique* (Janet, 1889)', refs: ['Janet Before Freud'] },
      { name: '*The Midnight Disease* (Flaherty, 2004)', refs: ['The Midnight Disease'] },
      { name: '*The Necessary and Sufficient Conditions of Therapeutic Personality Change* (Rogers, 1957)', refs: ['The Listening'] },
      { name: '*The Organization of Behavior* (Hebb, 1949)', refs: ['The Hebbian Principle'] },
      { name: '*Reclaiming Conversation* (Turkle, 2015)', refs: ['Turkle’s Continuation'] },
      { name: '*Schedules of Reinforcement* (Ferster & Skinner, 1957)', refs: ['Variable-Ratio Reinforcement'] },
      { name: '*The Stories We Live By* (McAdams, 1993)', refs: ['Narrative Identity'] },
      { name: '*The Terminal Man* (Crichton, 1972)', refs: ['The Terminal Man'] },
      { name: '*Unlocking the Emotional Brain* (Ecker, Ticic, Hulley, 2012)', refs: ['Coherence Therapy'] }
    ]
  },
  {
    category: 'Cases & Statutes',
    entries: [
      { name: 'CAPTA (Child Abuse Prevention and Treatment Act, 1974)', refs: ['CAPTA and the Reporter Class'] },
      { name: 'Community Mental Health Act (1963)', refs: ['Routes When ABC Does Not Fit'] },
      { name: 'Garcia v. Character Technologies (2024)', refs: ['Garcia v. Character Technologies'] },
      { name: 'HB 4002 (Oregon, 2024)', refs: ['HB 4002'] },
      { name: 'Jaffee v. Redmond (1996)', refs: ['Therapeutic Privilege'] },
      { name: 'Measure 110 (Oregon, 2020)', refs: ['Measure 110'] },
      { name: 'Mink v. Oregon State Hospital (2002)', refs: ['Mink v. Oregon State Hospital'] },
      { name: 'Tarasoff v. Regents of the University of California (1976)', refs: ['Tarasoff'] }
    ]
  },
  {
    category: 'Organizations & Programs',
    entries: [
      { name: 'AA (Alcoholics Anonymous)', refs: ['A Searching and Fearless Inventory'] },
      { name: 'AAPC (American Association of Pastoral Counselors)', refs: ['Routes When ABC Does Not Fit'] },
      { name: 'ABC (Association of Biblical Counselors)', refs: ['ABC'] },
      { name: 'Anthropic', refs: ['Alignment Is a Tax', 'Sycophancy'] },
      { name: 'Apollo Research', refs: ['Scheming'] },
      { name: 'CAHOOTS', refs: ['CAHOOTS'] },
      { name: 'Character.ai / Character Technologies', refs: ['Garcia v. Character Technologies'] },
      { name: 'Chai (app)', refs: ['AI-Induced Delusion'] },
      { name: 'Coordinated Care Organizations (Oregon)', refs: ['Coordinated Care Organizations'] },
      { name: 'DMS (Default Mode Network) — see Concepts', refs: [] },
      { name: 'ELIZA', refs: ['ELIZA', 'The Secretary', 'Judgment, Not Calculation', 'The ELIZA Effect'] },
      { name: 'Instagram', refs: ['What Meta Knew'] },
      { name: 'Meta', refs: ['What Meta Knew'] },
      { name: 'MIT', refs: ['ELIZA'] },
      { name: 'Open Path Collective', refs: ['Routes When ABC Does Not Fit'] },
      { name: 'Oregon Health Authority', refs: ['Measure 110'] },
      { name: 'OHSU (Oregon Health & Science University)', refs: ['Coordinated Care Organizations'] },
      { name: 'Portland Bureau of Fire & Rescue', refs: ['Portland Street Response'] },
      { name: 'Portland State University', refs: ['Portland Street Response'] },
      { name: 'Portland Street Response', refs: ['Portland Street Response'] },
      { name: 'RAND Corporation', refs: ['Measure 110'] },
      { name: 'Replika', refs: ['Replika’s Breakup'] },
      { name: 'White Bird Clinic (Eugene)', refs: ['CAHOOTS'] }
    ]
  },
  {
    category: 'Concepts',
    entries: [
      { name: 'Agentic drift', refs: ['Agentic Drift'] },
      { name: 'AI-induced delusion', refs: ['AI-Induced Delusion'] },
      { name: 'Alignment (AI)', refs: ['Alignment Is a Tax'] },
      { name: 'Big Book (AA)', refs: ['A Searching and Fearless Inventory'] },
      { name: 'Brain-computer interface', refs: ['The Terminal Man'] },
      { name: 'Autonomy (SDT)', refs: ['Self-Determination'] },
      { name: 'Braille / visual cortex repurposing', refs: ['Blind V1 Reads Braille'] },
      { name: 'Cognitive load', refs: ['Cognitive Load'] },
      { name: 'Coherence Therapy', refs: ['Coherence Therapy'] },
      { name: 'Compartmentalization', refs: ['Vaillant’s Hierarchy'] },
      { name: 'Consolidation (memory)', refs: ['Consolidation'] },
      { name: 'Constitutional AI', refs: ['Alignment Is a Tax'] },
      { name: 'Contagion (social)', refs: ['Contagion'] },
      { name: 'Cortical remapping', refs: ['Cortical Remapping'] },
      { name: 'Cortisol', refs: ['The Cortisol Aperture'] },
      { name: 'Default mode network', refs: ['Flow and the Default Mode'] },
      { name: 'Déjà vu', refs: ['A Memory Verification Error', 'The Scanner Finding', 'The Gestalt Hypothesis', 'The Temporal Lobe', 'Healthy by Default'] },
      { name: 'Dissociation', refs: ['Janet Before Freud', 'The Dissociation Spectrum', 'Structural Dissociation'] },
      { name: 'Dissociative amnesia', refs: ['Dissociative Amnesia'] },
      { name: 'Dissociative identity disorder', refs: ['The Dissociation Spectrum'] },
      { name: 'Dopamine', refs: ['The Midnight Disease'] },
      { name: 'DSM-5', refs: ['Dissociative Amnesia'] },
      { name: 'ELIZA effect', refs: ['The ELIZA Effect'] },
      { name: 'EMDR', refs: ['EMDR'] },
      { name: 'Expressive writing', refs: ['Pennebaker’s Paradigm', 'The Writing Protocol', 'A Searching and Fearless Inventory'] },
      { name: 'False memory', refs: ['Loftus and the Mall', 'The False Memory Wars'] },
      { name: 'Flow', refs: ['Flow and the Default Mode'] },
      { name: 'Four Horsemen', refs: ['The Four Horsemen'] },
      { name: 'Fourth Step (AA)', refs: ['A Searching and Fearless Inventory'] },
      { name: 'For You Page', refs: ['Contagion', 'Recommender Pathways'] },
      { name: 'Glymphatic system', refs: ['The Glymphatic Sweep'] },
      { name: 'Hebbian principle', refs: ['The Hebbian Principle'] },
      { name: 'Hypergraphia', refs: ['The Midnight Disease'] },
      { name: 'Identity-based cognition', refs: ['Identity-Based Cognition', 'Grounding in Identity'] },
      { name: 'IFS (Internal Family Systems)', refs: ['Internal Family Systems'] },
      { name: 'Long-term potentiation / depression', refs: ['Synaptic Memory'] },
      { name: 'Memory — reconsolidation', refs: ['Reconsolidation', 'The Labile State', 'Prediction Error Opens It'] },
      { name: 'Metacognitive therapy', refs: ['Metacognitive Distance'] },
      { name: 'Narrative identity', refs: ['Narrative Identity'] },
      { name: 'Neuroplasticity', refs: ['The Hebbian Principle', 'Synaptic Memory', 'Cortical Remapping', 'Blind V1 Reads Braille', 'Constraint-Induced Recovery'] },
      { name: 'Papageno effect', refs: ['Contagion'] },
      { name: 'Parts work (IFS)', refs: ['Internal Family Systems'] },
      { name: 'Peer support (certified)', refs: ['Certified Peer-Support Specialists'] },
      { name: 'Place cells', refs: ['Sleep and Replay'] },
      { name: 'Prediction error (reconsolidation)', refs: ['Prediction Error Opens It'] },
      { name: 'Reappraisal (cognitive)', refs: ['Reappraisal Beats Suppression', 'The At-Will Shift'] },
      { name: 'Redemption sequence (narrative)', refs: ['Narrative Identity'] },
      { name: 'Relatedness (SDT)', refs: ['Self-Determination'] },
      { name: 'Replay (hippocampal)', refs: ['Sleep and Replay'] },
      { name: 'RLHF (reinforcement learning from human feedback)', refs: ['Alignment Is a Tax', 'Sycophancy'] },
      { name: 'Rumination', refs: ['The Rumination Trap'] },
      { name: 'Scheming (AI)', refs: ['Scheming'] },
      { name: 'Self-compassion', refs: ['Self-Compassion'] },
      { name: 'Self-determination theory', refs: ['Self-Determination'] },
      { name: 'Sleep and memory', refs: ['Sleep and Replay', 'The Glymphatic Sweep'] },
      { name: 'State-dependent retrieval', refs: ['State-Dependent Retrieval'] },
      { name: 'Structural dissociation', refs: ['Structural Dissociation'] },
      { name: 'Suppression (thought)', refs: ['Suppression Costs', 'Reappraisal Beats Suppression'] },
      { name: 'Sycophancy (AI)', refs: ['Sycophancy'] },
      { name: 'Temporal lobe', refs: ['The Temporal Lobe', 'The Midnight Disease'] },
      { name: 'Tokens (language-model)', refs: ['Tokens, Not Thoughts'] },
      { name: 'Transformer architecture', refs: ['Tokens, Not Thoughts'] },
      { name: 'Turning toward (Gottman)', refs: ['Turning Toward the Bid', 'Turning Toward'] },
      { name: 'Twelve Steps (AA)', refs: ['A Searching and Fearless Inventory'] },
      { name: 'Unconditional positive regard', refs: ['The Listening'] },
      { name: 'Variable-ratio reinforcement', refs: ['Variable-Ratio Reinforcement', 'The Terminal Man'] },
      { name: 'Werther effect', refs: ['Contagion'] },
      { name: 'White bear (Wegner)', refs: ['Suppression Costs'] }
    ]
  }
];
